# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
records = Record.create([
{problem:'Head Injury',b_part:'1',  event_date:'2/2/2012',location:'New York, NY'  , status:'Ongoing',  provider: 'Dr Smith', comments:'This is an injury comment'},
{problem:'Head Injury2',b_part:'1',  event_date:'2/2/2017',location:'New York, NY'  , status:'Ongoing',  provider: 'Dr Smith', comments:'This is an injury comment '},
{problem:'Head Injury3',b_part:'1',  event_date:'8/2/2012',location:'New York, NY'  , status:'Ongoing',  provider: 'Dr Smith', comments:'This is an injury comment'},
{problem:'Head Injury4',b_part:'1',  event_date:'9/2/2017',location:'New York, NY'  , status:'Ongoing',  provider: 'Dr Smith', comments:'This is an injury comment '},
{problem:'Head Injury5',b_part:'1',  event_date:'10/2/2012',location:'New York, NY'  , status:'Ongoing',  provider: 'Dr Smith', comments:'This is an injury comment'},
{problem:'Head Injury6',b_part:'1',  event_date:'11/12/2017',location:'New York, NY'  , status:'Ongoing',  provider: 'Dr Smith', comments:'This is an injury comment '},

{problem:'Arm Injury',b_part:'2',  event_date:'2/2/2013',location:'New York, NY'  , status:'Treated',  provider: 'Dr Joe', comments:'This is an injury comment'},
{problem:'Arm Injury2',b_part:'2',  event_date:'2/2/2017',location:'New York, NY'  , status:'Treated',  provider: 'Dr Joe', comments:'This is an injury comment '},
{problem:'Arm Injury3',b_part:'2',  event_date:'8/2/2013',location:'New York, NY'  , status:'Treated',  provider: 'Dr Joe', comments:'This is an injury comment'},
{problem:'Arm Injury4',b_part:'2',  event_date:'9/2/2017',location:'New York, NY'  , status:'Treated',  provider: 'Dr Joe', comments:'This is an injury comment '},
{problem:'Arm Injury5',b_part:'2',  event_date:'10/2/2013',location:'New York, NY'  , status:'Treated',  provider: 'Dr Joe', comments:'This is an injury comment'},
{problem:'Arm Injury6',b_part:'2',  event_date:'11/12/2017',location:'New York, NY'  , status:'Treated',  provider: 'Dr Joe', comments:'This is an injury comment '},

{problem:'Chest Injury1',b_part:'3',  event_date:'4/4/2014',location:'New York, NY'  , status:'Treated',  provider: 'Dr Smith', comments:'This is an injury comment'},
{problem:'Chest Injury2',b_part:'3',  event_date:'4/4/2017',location:'New York, NY'  , status:'Treated',  provider: 'Dr Smith', comments:'This is an injury comment '},
{problem:'Chest Injury3',b_part:'3',  event_date:'8/4/2014',location:'New York, NY'  , status:'Treated',  provider: 'Dr Smith', comments:'This is an injury comment'},
{problem:'Chest Injury4',b_part:'3',  event_date:'9/4/2017',location:'New York, NY'  , status:'Treated',  provider: 'Dr Smith', comments:'This is an injury comment '},
{problem:'Chest Injury5',b_part:'3',  event_date:'10/4/2014',location:'New York, NY'  , status:'Treated',  provider: 'Dr Smith', comments:'This is an injury comment'},
{problem:'Chest Injury6',b_part:'3',  event_date:'11/14/2017',location:'New York, NY'  , status:'Treated',  provider: 'Dr Smith', comments:'This is an injury comment '},

{problem:'Upper Back1',  b_part:'4',  event_date:'6/4/2017' ,  location:'Dallas, Tx'  , status:'Ongoing', provider: 'Dr Smith', comments:'This is an injury comment '},
{problem:'Upper Back2',  b_part:'4',  event_date:'6/13/2017' ,  location:'Dallas, Tx'  , status:'Ongoing', provider: 'Dr Smith', comments:'This is an injury comment '},
{problem:'Upper Back3',  b_part:'4',  event_date:'6/17/2017' ,  location:'Dallas, Tx'  , status:'Ongoing', provider: 'Dr Smith', comments:'This is an injury comment '},
{problem:'Upper Back4',  b_part:'4',  event_date:'3/6/2017' ,  location:'Dallas, Tx'  , status:'Ongoing', provider: 'Dr Smith', comments:'This is an injury comment '},
{problem:'Upper Back5',  b_part:'4',  event_date:'7/6/2017' ,  location:'Dallas, Tx'  , status:'Ongoing', provider: 'Dr Smith', comments:'This is an injury comment '},
{problem:'Upper Back6',  b_part:'4',  event_date:'3/8/2017' ,  location:'Dallas, Tx'  , status:'Ongoing', provider: 'Dr Smith', comments:'This is an injury comment '},
{problem:'Upper Back7',  b_part:'4',  event_date:'4/6/2017' ,  location:'Dallas, Tx'  , status:'Ongoing', provider: 'Dr Smith', comments:'This is an injury comment '},

{problem:'Lower Back1',b_part:'5',  event_date:'6/4/2017',location:'Dallas, Tx'  , status:'Ongoing', provider: 'Dr Smith', comments:'This is an injury comment '},
{problem:'Lower Back2',b_part:'5',  event_date:'6/4/2017',location:'Dallas, Tx'  , status:'Ongoing', provider: 'Dr Smith', comments:'This is an injury comment '},
{problem:'Lower Back3',b_part:'5',  event_date:'6/4/2017',location:'Dallas, Tx'  , status:'Ongoing', provider: 'Dr Smith', comments:'This is an injury comment '},
{problem:'Lower Back4',b_part:'5',  event_date:'6/4/2017',location:'Dallas, Tx'  , status:'Ongoing', provider: 'Dr Smith', comments:'This is an injury comment '},
{problem:'Lower Back5',b_part:'5',  event_date:'6/4/2017',location:'Dallas, Tx'  , status:'Ongoing', provider: 'Dr Smith', comments:'This is an injury comment '},
{problem:'Lower Back6',b_part:'5',  event_date:'6/4/2017',location:'Dallas, Tx'  , status:'Ongoing', provider: 'Dr Smith', comments:'This is an injury comment '},
{problem:'Lower Back7',b_part:'5',  event_date:'6/4/2017',location:'Dallas, Tx'  , status:'Ongoing', provider: 'Dr Smith', comments:'This is an injury comment '},

{problem:'Leg Injury1',b_part:'6',  event_date:'5/5/2015',location:'Dallas, Tx'  , status:'Resolved' , provider: 'Dr Joe', comments:'This is an injury comment'},
{problem:'Leg Injury2',b_part:'6',  event_date:'5/5/2017',location:'Dallas, Tx'  , status:'Resolved' , provider: 'Dr Joe', comments:'This is an injury comment '},
{problem:'Leg Injury3',b_part:'6',  event_date:'8/5/2015',location:'Dallas, Tx'  , status:'Resolved' , provider: 'Dr Joe', comments:'This is an injury comment'},
{problem:'Leg Injury4',b_part:'6',  event_date:'9/5/2017',location:'Dallas, Tx'  , status:'Resolved' , provider: 'Dr Joe', comments:'This is an injury comment '},
{problem:'Leg Injury5',b_part:'6',  event_date:'10/5/2015',location:'Dallas, Tx'  , status:'Resolved' , provider: 'Dr Joe', comments:'This is an injury comment'},
{problem:'Leg Injury6',b_part:'6',  event_date:'11/15/2017',location:'Dallas, Tx'  , status:'Resolved' , provider: 'Dr Joe', comments:'This is an injury comment '},

{problem:'Illness1',b_part:'7',  event_date:'6/6/2016',location:'Dallas, Tx'  , status:'Ongoing', provider: 'Dr Smith', comments:'This is an injury comment'},
{problem:'Illness2',b_part:'7',  event_date:'6/6/2017',location:'Dallas, Tx'  , status:'Ongoing', provider: 'Dr Smith', comments:'This is an injury comment '},
{problem:'Illness3',b_part:'7',  event_date:'8/6/2016',location:'Dallas, Tx'  , status:'Ongoing', provider: 'Dr Smith', comments:'This is an injury comment'},
{problem:'Illness4',b_part:'7',  event_date:'9/6/2017',location:'Dallas, Tx'  , status:'Ongoing', provider: 'Dr Smith', comments:'This is an injury comment '},
{problem:'Illness5',b_part:'7',  event_date:'10/6/2016',location:'Dallas, Tx'  , status:'Ongoing', provider: 'Dr Smith', comments:'This is an injury comment'},
{problem:'Illness6',b_part:'7',  event_date:'11/16/2017',location:'Dallas, Tx'  , status:'Ongoing', provider: 'Dr Smith', comments:'This is an injury comment '}
])




medications = Medication.create([
{
    package_label_principal_display_panel: "PRINCIPAL DISPLAY PANEL - 20 mg NDC 66336-0722-XX NDC 66336-0722-30 Omeprazole Delayed-release Capsules, USP 20 mg PHARMACIST: Dispense the accompanying Medication Guide to each patient. Rx only Each capsule contains: Omeprazole, USP 20 mg Dispense in a tight, light-resistant container as defined in the USP using a child-resistant closure. Keep container tightly closed. Keep this and all medication out of the reach of children. Store at 20\u00b0 to 25\u00b0C (68\u00b0 to 77\u00b0F). [See USP Controlled Room Temperature.] Protect from light and moisture. Usual Dosage: See accompanying prescribing information. The omeprazole delayed-release capsule should be swallowed whole and not opened, chewed, or crushed. Jointly manufactured by: Mylan Pharmaceuticals Inc. Morgantown, WV 26505 U.S.A. and Laboratorios Dr. Esteve, S.A. 08107 Martorelles (Barcelona), Spain RM6150H11 NDC 66336-0706-XX" ,
    manufacturer_name: "Dispensing Solutions, Inc." ,
    unii: "KG60484QX9" ,
    product_type: "HUMAN PRESCRIPTION DRUG" ,
    rxcui: "198051" ,
    spl_set_id: "8e3b29b0-d3a8-409a-b397-53dbbbcda094" ,
    route: "ORAL" ,
    generic_name: "OMEPRAZOLE" ,
    brand_name: "Omeprazole" ,
    product_ndc: "66336-706" ,
    original_packager_product_ndc: "0378-6150" ,
    substance_name: "OMEPRAZOLE" ,
    spl_id: "64218455-e1e2-4e40-bd32-5002d2d1555d" ,
    pharm_class_moa: "Proton Pump Inhibitors MoA",
    pharm_class_pe: "",
    application_number: "ANDA075876" ,
    nui: "N0000175525",
    pharm_class_epc: "Proton Pump Inhibitor EPC" ,
    package_ndc: "66336-706-30",
    indications_and_usage: "1 INDICATIONS AND USAGE Omeprazole is a proton pump inhibitor indicated for: Treatment in adults of duodenal ulcer (1.1) and gastric ulcer (1.2) Treatment in adults and children of gastroesophageal reflux disease (GERD) (1.3) and maintenance of healing of erosive esophagitis (1.4) The safety and effectiveness of omeprazole in pediatric patients < 1 year of age have not been established. (8.4) 1.1 Duodenal Ulcer (adults) Omeprazole delayed-release capsules are indicated for short-term treatment of active duodenal ulcer in adults. Most patients heal within 4 weeks. Some patients may require an additional 4 weeks of therapy. Omeprazole delayed-release capsules, in combination with clarithromycin and amoxicillin, are indicated for treatment of patients with H. pylori infection and duodenal ulcer disease (active or up to one year history) to eradicate H. pylori in adults. Omeprazole delayed-release capsules, in combination with clarithromycin are indicated for treatment of patients with H. pylori infection and duodenal ulcer disease to eradicate H. pylori in adults. Eradication of H. pylori has been shown to reduce the risk of duodenal ulcer recurrence [see Clinical Studies (14.1) and Dosage and Administration (2)]. Among patients who fail therapy, omeprazole delayed-release capsules with clarithromycin are more likely to be associated with the development of clarithromycin resistance as compared with triple therapy. In patients who fail therapy, susceptibility testing should be done. If resistance to clarithromycin is demonstrated or susceptibility testing is not possible, alternative antimicrobial therapy should be instituted [see Microbiology section (12.4) and the clarithromycin package insert, Microbiology section]. 1.2 Gastric Ulcer (adults) Omeprazole delayed-release capsules are indicated for short-term treatment (4 to 8 weeks) of active benign gastric ulcer in adults [see Clinical Studies (14.2)]. 1.3 Treatment of Gastroesophageal Reflux Disease (GERD) (adults and pediatric patients) Symptomatic GERD Omeprazole delayed-release capsules are indicated for the treatment of heartburn and other symptoms associated with GERD in pediatric patients and adults. Erosive Esophagitis Omeprazole delayed-release capsules are indicated for the short-term treatment (4 to 8 weeks) of erosive esophagitis that has been diagnosed by endoscopy in pediatric patients and adults [see Clinical Studies (14.4)]. The efficacy of omeprazole delayed-release capsules used for longer than 8 weeks in these patients has not been established. If a patient does not respond to 8 weeks of treatment, an additional 4 weeks of treatment may be given. If there is recurrence of erosive esophagitis or GERD symptoms (e.g., heartburn), additional 4 to 8 week courses of omeprazole may be considered. 1.4 Maintenance of Healing of Erosive Esophagitis (adults and pediatric patients) Omeprazole delayed-release capsules are indicated to maintain healing of erosive esophagitis in pediatric patients and adults. Controlled studies do not extend beyond 12 months [see Clinical Studies (14.4)]. 1.5 Pathological Hypersecretory Conditions (adults) Omeprazole delayed-release capsules are indicated for the long-term treatment of pathological hypersecretory conditions (e.g., Zollinger-Ellison syndrome, multiple endocrine adenomas and systemic mastocytosis) in adults." ,
  dosage_and_administration: "2 DOSAGE AND ADMINISTRATION Omeprazole delayed-release capsules should be taken before eating. In the clinical trials, antacids were used concomitantly with omeprazole delayed-release capsules. Patients should be informed that the omeprazole delayed-release capsules should be swallowed whole. For patients unable to swallow an intact capsule, alternative administration options are available [see Dosage and Administration (2.8)]. Indication Omeprazole Dose Frequency Treatment of Active Duodenal Ulcer (2.1) 20 mg Once daily for 4 weeks. Some patients may require an additional 4 weeks H. pylori Eradication to Reduce the Risk of Duodenal Ulcer Recurrence (2.2) Triple Therapy: Omeprazole 20 mg Each drug twice Amoxicillin 1000 mg daily for 10 days Clarithromycin 500 mg Dual Therapy: Omeprazole 40 mg Once daily for 14 days Clarithromycin 500 mg Three times daily for 14 days Gastric Ulcer (2.3) 40 mg Once daily for 4 to 8 weeks GERD (2.4) 20 mg Once daily for 4 to 8 weeks Maintenance of Healing of Erosive Esophagitis (2.5) 20 mg Once daily Pathological Hypersecretory Conditions (2.6) 60 mg (varies with individual patient) Once daily Pediatric Patients (2 to 16 years of age) (2.7) Weight Dose GERD and 10 < 20 kg 10 mg Once daily Maintenance of \u2265 20 kg 20 mg Healing of Erosive Esophagitis 2.1 Short-Term Treatment of Active Duodenal Ulcer The recommended adult oral dose of omeprazole delayed-release capsules is 20 mg once daily. Most patients heal within 4 weeks. Some patients may require an additional 4 weeks of therapy. 2.2 H. pylori Eradication for the Reduction of the Risk of Duodenal Ulcer Recurrence Triple Therapy (omeprazole/clarithromycin/amoxicillin) The recommended adult oral regimen is omeprazole delayed-release capsules 20 mg plus clarithromycin 500 mg plus amoxicillin 1000 mg each given twice daily for 10 days. In patients with an ulcer present at the time of initiation of therapy, an additional 18 days of omeprazole delayed-release capsules 20 mg once daily is recommended for ulcer healing and symptom relief. Dual Therapy (omeprazole/clarithromycin) The recommended adult oral regimen is omeprazole delayed-release capsules 40 mg once daily plus clarithromycin 500 mg 3 times daily for 14 days. In patients with an ulcer present at the time of initiation of therapy, an additional 14 days of omeprazole delayed-release capsules 20 mg once daily is recommended for ulcer healing and symptom relief. 2.3 Gastric Ulcer The recommended adult oral dose is 40 mg once daily for 4 to 8 weeks. 2.4 Gastroesophageal Reflux Disease (GERD) The recommended adult oral dose for the treatment of patients with symptomatic GERD and no esophageal lesions is 20 mg daily for up to 4 weeks. The recommended adult oral dose for the treatment of patients with erosive esophagitis and accompanying symptoms due to GERD is 20 mg daily for 4 to 8 weeks. 2.5 Maintenance of Healing of Erosive Esophagitis The recommended adult oral dose is 20 mg daily [see Clinical Studies (14.4)]. 2.6 Pathological Hypersecretory Conditions The dosage of omeprazole delayed-release capsules in patients with pathological hypersecretory conditions varies with the individual patient. The recommended adult oral starting dose is 60 mg once daily. Doses should be adjusted to individual patient needs and should continue for as long as clinically indicated. Doses up to 120 mg three times daily have been administered. Daily dosages of greater than 80 mg should be administered in divided doses. Some patients with Zollinger-Ellison syndrome have been treated continuously with omeprazole delayed-release capsules for more than 5 years. 2.7 Pediatric Patients For the treatment of GERD and maintenance of healing of erosive esophagitis, the recommended daily dose for pediatric patients 2 to 16 years of age is as follows: Patient Weight Omeprazole Daily Dose 10 < 20 kg 10 mg \u2265 20 kg 20 mg On a per kg basis, the doses of omeprazole delayed-release capsules required to heal erosive esophagitis in pediatric patients are greater than those for adults. Alternative administrative options can be used for pediatric patients unable to swallow an intact capsule [see Dosage and Administration (2.8)]. 2.8 Alternative Administration Options Omeprazole is available as a delayed-release capsule. For patients who have difficulty swallowing capsules, the contents of an omeprazole delayed-release capsule can be added to applesauce. One tablespoon of applesauce should be added to an empty bowl and the capsule should be opened. All of the pellets inside the capsule should be carefully emptied on the applesauce. The pellets should be mixed with the applesauce and then swallowed immediately with a glass of cool water to ensure complete swallowing of the pellets. The applesauce used should not be hot and should be soft enough to be swallowed without chewing. The pellets should not be chewed or crushed. The pellets/applesauce mixture should not be stored for future use."
 },
{
  package_label_principal_display_panel: "PRINCIPAL DISPLAY PANEL NDC 55045-1433-04 NDC 55045-1433-04" ,
  manufacturer_name: "Dispensing Solutions, Inc.",
  unii: "21925K482H",
  product_type: "HUMAN PRESCRIPTION DRUG",
  rxcui: "197446",
  spl_set_id: "b677267d-45ce-4f08-ac90-2bb6dcde8978",
  route: "ORAL",
  generic_name: "CARISOPRODOL",
  brand_name: "Carisoprodol",
  pharm_class_pe: "Centrally-mediated Muscle Relaxation PE",
  product_ndc: "55045-1433",
  original_packager_product_ndc: "0603-2582",
  substance_name: "CARISOPRODOL",
  spl_id: "667d0cdd-ff0b-45fa-a089-d7f563bbbda8",
  application_number: "ANDA040245",
  nui: "N0000175737",
  pharm_class_epc: "Muscle Relaxant",
  package_ndc: "55045-1433-4",
  indications_and_usage:  "1 INDICATIONS AND USAGE Carisoprodol Tablets are indicated for the relief of discomfort associated with acute, painful musculoskeletal conditions in adults. Carisoprodol Tablets should only be used for short periods (up to two or three weeks) because adequate evidence of effectiveness for more prolonged use has not been established and because acute, painful musculoskeletal conditions are generally of short duration [see Dosage and Administration (2) ]. Carisoprodol Tablets are indicated for the relief of discomfort associated with acute, painful musculoskeletal conditions in adults. (1) Limitations of Use: Should only be used for acute treatment periods up to two or three weeks (1)",
  dosage_and_administration: "2 DOSAGE AND ADMINISTRATION The recommended dose of carisoprodol is 250 mg to 350 mg three times a day and at bedtime. The recommended maximum duration of carisoprodol use is up to two or three weeks. Recommended dose is 250 mg to 350 mg three times a day and at bedtime. (2)" ,
},

{
  package_label_principal_display_panel: "PACKAGE LABEL.PRINCIPAL DISPLAY PANEL NDC 66336-0815-XX NDC 66336-0815-30 NDC 66336-0815-60 Pharmacist: Dispense the Medication Guide provided separately to each patient. NDC 66336-0815-XX",
  manufacturer_name:  "Dispensing Solutions, Inc.",
  unii: "57Y76R9ATQ",
  product_type: "HUMAN PRESCRIPTION DRUG",
  rxcui: "198014",
  spl_set_id: "2077556d-29f3-469e-8fab-1d9dc7820b6d",
  route: "ORAL",
  generic_name: "NAPROXEN",
  brand_name: "NAPROXEN",
  product_ndc: "66336-815",
  original_packager_product_ndc: "52605-140",
  substance_name: "NAPROXEN",
  spl_id: "f9f24b7c-2184-463c-bd18-70edd0b271db",
  pharm_class_moa: "Cyclooxygenase Inhibitors MoA",
  application_number: "ANDA091416",
  nui: "N0000000160",
  pharm_class_epc: "Nonsteroidal Anti-inflammatory Drug EPC",
  package_ndc: "66336-815-30",
  indications_and_usage: "INDICATIONS & USAGE Carefully consider the potential benefits and risks of naproxen and other treatment options before deciding to use naproxen tablets. Use the lowest effective dose for the shortest duration consistent with individual patient treatment goals (see WARNINGS ). Naproxen tablets are indicated: For the relief of the signs and symptoms of rheumatoid arthritis For the relief of the signs and symptoms of osteoarthritis For the relief of the signs and symptoms of ankylosing spondylitis For the relief of the signs and symptoms of juvenilearthritis Naproxen tablets are also indicated: For relief of the signs and symptoms of tendonitis For relief of the signs and symptoms of bursitis For relief of the signs and symptoms of acute gout For the management of pain For the management of primary dysmenorrhea",
  dosage_and_administration:  "DOSAGE & ADMINISTRATION Carefully consider the potential benefits and risks of naproxen and other treatment options before deciding to use naproxen tablets. Use the lowest effective dose for the shortest duration consistent with individual patient treatment goals (see WARNINGS). After observing the response to initial therapy with naproxen tablets, the dose and frequency should be adjusted to suit an individual patient's needs. Different dose strengths and formulations (i.e., tablets, suspension) of the drug are not necessarily bioequivalent. This difference should be taken into consideration when changing formulation. Although naproxen tablets, naproxen suspension, naproxen delayed-released tablets, and naproxen sodium tablets all circulate in the plasma as naproxen, they have pharmacokinetic differences that may affect onset of action. Onset of pain relief can begin within 1 hour in patients taking naproxen. The recommended strategy for initiating therapy is to choose a formulation and a starting dose likely to be effective for the patient and then adjust the dosage based on observation of benefit and/or adverse events. A lower dose should be considered in patients with renal or hepatic impairment or in elderly patients (see WARNINGS and PRECAUTIONS). Geriatric Patients Studies indicate that although total plasma concentration of naproxen is unchanged, the unbound plasma fraction of naproxen is increased in the elderly. Caution is advised when high doses are required and some adjustment of dosage may be required in elderly patients. As with other drugs used in the elderly, it is prudent to use the lowest effective dose. Patients With Moderate to Severe Renal Impairment Naproxen-containing products are not recommended for use in patients with moderate to severe and severe renal impairment (creatinine clearance < 30 mL/min) (see WARNINGS: Renal Effects). Rheumatoid Arthritis, Osteoarthritis and Ankylosing Spondylitis The recommended dose is 250 mg, 375 mg, or 500 mg twice daily. During long-term administration, the dose of naproxen may be adjusted up or down depending on the clinical response of the patient. A lower daily dose may suffice for long-term administration. The morning and evening doses do not have to be equal in size and the administration of the drug more frequently than twice daily is not necessary. In patients who tolerate lower doses well, the dose may be increased to naproxen 1500 mg/day for limited periods of up to 6 months when a higher level of anti-inflammatory/analgesic activity is required. When treating such patients with naproxen 1500 mg/day, the physician should observe sufficient increased clinical benefits to offset the potential increased risk. The morning and evening doses do not have to be equal in size and administration of the drug more frequently than twice daily does not generally make a difference in response (see CLINICAL PHARMACOLOGY). Juvenile Arthritis The recommended total daily dose of naproxen is approximately 10 mg/kg given in 2 divided doses (i.e., 5 mg/kg given twice a day). Naproxen tablets are not well suited to this dosage so use of naproxen oral suspension is recommended for this indication. Management of Pain, Primary Dysmenorrhea, and Acute Tendonitis and Bursitis Because the sodium salt of naproxen is more rapidly absorbed, naproxen sodium is recommended for the management of acute painful conditions when prompt onset of pain relief is desired. Naproxen may also be used. The recommended starting dose of naproxen is 500 mg, followed by 500 mg every 12 hours or 250 mg every 6 to 8 hours as required. The initial total daily dose should not exceed 1250 mg of naproxen. Thereafter, the total daily dose should not exceed 1000 mg of naproxen. Acute Gout The recommended starting dose is 750 mg of naproxen followed by 250 mg every 8 hours until the attack has subsided.",
  description:  "DESCRIPTION Naproxen is a proprionic acid derivative related to the arylacetic acid group of nonsteroidal anti-inflammatory drugs. The chemical name for naproxen is (S)-6-methoxy-\u26d9-methyl-2-naphthaleneacetic acid. It has the following structure: Molecular Formula: C14H14O3 MW = 230.26 Naproxen has a molecular weight of 230.26 and a molecular formula of C14H14O3. Naproxen is an odorless, white to off-white crystalline substance. It is lipid-soluble, practically insoluble in water at low pH and freely soluble in water at high pH. The octanol/water partition coefficient of naproxen at pH 7.4 is 1.6 to 1.8. Naproxen tablets are available as white tablets containing 500 mg of naproxen for oral administration. The inactive ingredients are croscarmellose sodium, povidone and magnesium stearate. naproxen chemical structure",
 },
{
 package_label_principal_display_panel: "package_label1" ,
 manufacturer_name: "manufacturer_name1" ,
 unii: "unii1" ,
 product_type: "product_type1" ,
 rxcui: "rxcui1" ,
 spl_set_id: "spl_set_id" ,
 route: "route1" ,
 generic_name: "generic_name1" ,
 brand_name: "brand_name1" ,
 product_ndc:"product_ndc1" ,
 original_packager_product_ndc:"original_packager1" ,
 substance_name: "substance_name1" ,
 spl_id: "spl_id1" ,
 pharm_class_moa:"pharm_class_moa1" ,
 pharm_class_pe: "pharm_class_pe1",
 application_number: "application_number1" ,
 nui:"nui1" ,
 pharm_class_epc:"pharm_class_epc1" ,
 package_ndc:"package_ndc1" ,
 indications_and_usage: "indications_and_usage1" ,
 dosage_and_administration:"dosage_and_administration1" ,
 description: "description1",
 },
{
 package_label_principal_display_panel: "package_label2" ,
 manufacturer_name: "manufacturer_name2" ,
 unii: "unii2" ,
 product_type: "product_type2" ,
 rxcui: "rxcui2" ,
 spl_set_id: "spl_set_id" ,
 route: "route2" ,
 generic_name: "generic_name2" ,
 brand_name: "brand_name2" ,
 product_ndc:"product_ndc2" ,
 original_packager_product_ndc:"original_packager2" ,
 substance_name: "substance_name2" ,
 spl_id: "spl_id2" ,
 pharm_class_moa:"pharm_class_moa2" ,
 pharm_class_pe: "pharm_class_pe2",
 application_number: "application_number2" ,
 nui:"nui2" ,
 pharm_class_epc:"pharm_class_epc2" ,
 package_ndc:"package_ndc2" ,
 indications_and_usage: "indications_and_usage2" ,
 dosage_and_administration:"dosage_and_administration2" ,
 description: "description2",
 },
{
 package_label_principal_display_panel: "package_label3" ,
 manufacturer_name: "manufacturer_name3" ,
 unii: "unii3" ,
 product_type: "product_type3" ,
 rxcui: "rxcui3" ,
 spl_set_id: "spl_set_id" ,
 route: "route3" ,
 generic_name: "generic_name3" ,
 brand_name: "brand_name3" ,
 product_ndc:"product_ndc3" ,
 original_packager_product_ndc:"original_packager3" ,
 substance_name: "substance_name3" ,
 spl_id: "spl_id3" ,
 pharm_class_moa:"pharm_class_moa3" ,
 pharm_class_pe: "pharm_class_pe3",
 application_number: "application_number3" ,
 nui:"nui3" ,
 pharm_class_epc:"pharm_class_epc3" ,
 package_ndc:"package_ndc3" ,
 indications_and_usage: "indications_and_usage3" ,
 dosage_and_administration:"dosage_and_administration3" ,
 description: "description3",
 },
{
 package_label_principal_display_panel: "package_label4" ,
 manufacturer_name: "manufacturer_name4" ,
 unii: "unii4" ,
 product_type: "product_type4" ,
 rxcui: "rxcui4" ,
 spl_set_id: "spl_set_id" ,
 route: "route4" ,
 generic_name: "generic_name4" ,
 brand_name: "brand_name4" ,
 product_ndc:"product_ndc4" ,
 original_packager_product_ndc:"original_packager4" ,
 substance_name: "substance_name4" ,
 spl_id: "spl_id4" ,
 pharm_class_moa:"pharm_class_moa4" ,
 pharm_class_pe: "pharm_class_pe4",
 application_number: "application_number4" ,
 nui:"nui4" ,
 pharm_class_epc:"pharm_class_epc4" ,
 package_ndc:"package_ndc4" ,
 indications_and_usage: "indications_and_usage4" ,
 dosage_and_administration:"dosage_and_administration4" ,
 description: "description4",
 },
 {
 package_label_principal_display_panel: "package_label5" ,
 manufacturer_name: "manufacturer_name5" ,
 unii: "unii5" ,
 product_type: "product_type5" ,
 rxcui: "rxcui5" ,
 spl_set_id: "spl_set_id" ,
 route: "route5" ,
 generic_name: "generic_name5" ,
 brand_name: "brand_name5" ,
 product_ndc:"product_ndc5" ,
 original_packager_product_ndc:"original_packager5" ,
 substance_name: "substance_name5" ,
 spl_id: "spl_id5" ,
 pharm_class_moa:"pharm_class_moa5" ,
 pharm_class_pe: "pharm_class_pe5",
 application_number: "application_number5" ,
 nui:"nui5" ,
 pharm_class_epc:"pharm_class_epc5" ,
 package_ndc:"package_ndc5" ,
 indications_and_usage: "indications_and_usage5" ,
 dosage_and_administration:"dosage_and_administration5" ,
 description: "description5",
 },
 {
 package_label_principal_display_panel: "package_label6" ,
 manufacturer_name: "manufacturer_name6" ,
 unii: "unii6" ,
 product_type: "product_type6" ,
 rxcui: "rxcui6" ,
 spl_set_id: "spl_set_id" ,
 route: "route6" ,
 generic_name: "generic_name6" ,
 brand_name: "brand_name6" ,
 product_ndc:"product_ndc6" ,
 original_packager_product_ndc:"original_packager6" ,
 substance_name: "substance_name6" ,
 spl_id: "spl_id6" ,
 pharm_class_moa:"pharm_class_moa6" ,
 pharm_class_pe: "pharm_class_pe6",
 application_number: "application_number6" ,
 nui:"nui6" ,
 pharm_class_epc:"pharm_class_epc6" ,
 package_ndc:"package_ndc6" ,
 indications_and_usage: "indications_and_usage6" ,
 dosage_and_administration:"dosage_and_administration6" ,
 description: "description6",
 },
 {
 package_label_principal_display_panel: "package_label7" ,
 manufacturer_name: "manufacturer_name7" ,
 unii: "unii7" ,
 product_type: "product_type7" ,
 rxcui: "rxcui7" ,
 spl_set_id: "spl_set_id" ,
 route: "route7" ,
 generic_name: "generic_name7" ,
 brand_name: "brand_name7" ,
 product_ndc:"product_ndc7" ,
 original_packager_product_ndc:"original_packager7" ,
 substance_name: "substance_name7" ,
 spl_id: "spl_id7" ,
 pharm_class_moa:"pharm_class_moa7" ,
 pharm_class_pe: "pharm_class_pe7",
 application_number: "application_number7" ,
 nui:"nui7" ,
 pharm_class_epc:"pharm_class_epc7" ,
 package_ndc:"package_ndc7" ,
 indications_and_usage: "indications_and_usage7" ,
 dosage_and_administration:"dosage_and_administration7" ,
 description: "description7",
 },
 {
 package_label_principal_display_panel: "package_label8" ,
 manufacturer_name: "manufacturer_name8" ,
 unii: "unii8" ,
 product_type: "product_type8" ,
 rxcui: "rxcui8" ,
 spl_set_id: "spl_set_id" ,
 route: "route8" ,
 generic_name: "generic_name8" ,
 brand_name: "brand_name8" ,
 product_ndc:"product_ndc8" ,
 original_packager_product_ndc:"original_packager8" ,
 substance_name: "substance_name8" ,
 spl_id: "spl_id8" ,
 pharm_class_moa:"pharm_class_moa8" ,
 pharm_class_pe: "pharm_class_pe8",
 application_number: "application_number8" ,
 nui:"nui8" ,
 pharm_class_epc:"pharm_class_epc8" ,
 package_ndc:"package_ndc8" ,
 indications_and_usage: "indications_and_usage8" ,
 dosage_and_administration:"dosage_and_administration8" ,
 description: "description8",
 },
 {
 package_label_principal_display_panel: "package_label9" ,
 manufacturer_name: "manufacturer_name9" ,
 unii: "unii9" ,
 product_type: "product_type9" ,
 rxcui: "rxcui9" ,
 spl_set_id: "spl_set_id" ,
 route: "route9" ,
 generic_name: "generic_name9" ,
 brand_name: "brand_name9" ,
 product_ndc:"product_ndc9" ,
 original_packager_product_ndc:"original_packager9" ,
 substance_name: "substance_name9" ,
 spl_id: "spl_id9" ,
 pharm_class_moa:"pharm_class_moa9" ,
 pharm_class_pe: "pharm_class_pe9",
 application_number: "application_number9" ,
 nui:"nui9" ,
 pharm_class_epc:"pharm_class_epc9" ,
 package_ndc:"package_ndc9" ,
 indications_and_usage: "indications_and_usage9" ,
 dosage_and_administration:"dosage_and_administration9" ,
 description: "description9",
 },
 {
 package_label_principal_display_panel: "package_label10" ,
 manufacturer_name: "manufacturer_name10" ,
 unii: "unii10" ,
 product_type: "product_type10" ,
 rxcui: "rxcui10" ,
 spl_set_id: "spl_set_id" ,
 route: "route10" ,
 generic_name: "generic_name10" ,
 brand_name: "brand_name10" ,
 product_ndc:"product_ndc10" ,
 original_packager_product_ndc:"original_packager10" ,
 substance_name: "substance_name10" ,
 spl_id: "spl_id10" ,
 pharm_class_moa:"pharm_class_moa10" ,
 pharm_class_pe: "pharm_class_pe10",
 application_number: "application_number10" ,
 nui:"nui10" ,
 pharm_class_epc:"pharm_class_epc10" ,
 package_ndc:"package_ndc10" ,
 indications_and_usage: "indications_and_usage10" ,
 dosage_and_administration:"dosage_and_administration10" ,
 description: "description10",
 },
 {
 package_label_principal_display_panel: "package_label11" ,
 manufacturer_name: "manufacturer_name11" ,
 unii: "unii11" ,
 product_type: "product_type11" ,
 rxcui: "rxcui11" ,
 spl_set_id: "spl_set_id" ,
 route: "route11" ,
 generic_name: "generic_name11" ,
 brand_name: "brand_name11" ,
 product_ndc:"product_ndc11" ,
 original_packager_product_ndc:"original_packager11" ,
 substance_name: "substance_name11" ,
 spl_id: "spl_id11" ,
 pharm_class_moa:"pharm_class_moa11" ,
 pharm_class_pe: "pharm_class_pe11",
 application_number: "application_number11" ,
 nui:"nui11" ,
 pharm_class_epc:"pharm_class_epc11" ,
 package_ndc:"package_ndc11" ,
 indications_and_usage: "indications_and_usage11" ,
 dosage_and_administration:"dosage_and_administration11" ,
 description: "description11",
 },
 {
 package_label_principal_display_panel: "package_label12" ,
 manufacturer_name: "manufacturer_name12" ,
 unii: "unii12" ,
 product_type: "product_type12" ,
 rxcui: "rxcui12" ,
 spl_set_id: "spl_set_id" ,
 route: "route12" ,
 generic_name: "generic_name12" ,
 brand_name: "brand_name12" ,
 product_ndc:"product_ndc12" ,
 original_packager_product_ndc:"original_packager12" ,
 substance_name: "substance_name12" ,
 spl_id: "spl_id12" ,
 pharm_class_moa:"pharm_class_moa12" ,
 pharm_class_pe: "pharm_class_pe12",
 application_number: "application_number12" ,
 nui:"nui12" ,
 pharm_class_epc:"pharm_class_epc12" ,
 package_ndc:"package_ndc12" ,
 indications_and_usage: "indications_and_usage12" ,
 dosage_and_administration:"dosage_and_administration12" ,
 description: "description12",
 }
])

